base_model: lmsys/vicuna-33b-v1.3
base_model_config: lmsys/vicuna-33b-v1.3
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

seed: 42

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: ShareGPT_Vicuna_unfiltered/ShareGPT_V4.3_unfiltered_cleaned_split.json
    type: sharegpt
dataset_prepared_path: /tmp/prepared-data
val_set_size: 0.01
output_dir: ./ckpts/medusa_vicuna_33b_qlora_stage2_sd_42

adapter: qlora

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - lm_head
lora_target_linear: 
lora_fan_in_fan_out:
lora_modules_to_save:
lora_model_dir: ./ckpts/medusa_vicuna_33b_qlora_stage1_sd_42

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

wandb_project: colm-hydra-decoding
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_name: medusa_vicuna_33b_qlora_stage2_sd_42
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0005

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 40
eval_steps: 40
save_steps:
save_total_limit: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

grounded_heads: false
hydra_head_arch: mlp
hydra_num_heads: 5
hydra_num_layers: 1
hydra_heads_coefficient: 0.2
hydra_decay_coefficient: 0.8
hydra_logging: true
hydra_scheduler: constant
hydra_lr_multiplier: 4.0
# hydra_only_heads: true
# ddp_find_unused_parameters: true
# Stage 1: only train the hydra heads
# Stage 2: train the whole model